apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: mypvc
      mountPath: /mnt/pvdata
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: pvc-demo   # <-- FIXED HERE

